### PR TITLE
chore: update all go deps

### PR DESCRIPTION
**Pull request by elliottneilclark**
Summary:
`bix go-update-deps`

Test:
CI

### CODE REVIEW

**Review by JTarasovic — APPROVED** [review]

**Comment by elliottneilclark** [comment]
@JTarasovic this looks like a goreleaser integration bug that's around github actions/PR.

The first clue is:

```
    • git state                                      commit=f007893cf629ce7d18b5ca25eb60d36808924ed4 branch=HEAD current_tag=v0.0.0 previous_tag=<unknown> dirty=false
```

The commit is actually `ce955234b7498f2d83097e351418926a7ac62c8c` and the branch is `elliott/update_go_deps` There are versions specified and previous version.

Then the failure is about running out of space in a specific dir. Likely goreleaser is expecting something to be larger than it is.

**Comment by elliottneilclark** [comment]
Other times this action have run have this warning:

```

You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 33 MB
```

**Comment by JTarasovic** [comment]
The checkout action checks out the merge commit so I think that the commit and branch would be expected...

```
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/974/merge
  Note: switching to 'refs/remotes/pull/974/merge'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at f007893 Merge ce955234b7498f2d83097e351418926a7ac62c8c into ce1995716ff81150aa956c61c3401af0b50d7edc
/usr/bin/git log -1 --format='%H'
'f007893cf629ce7d18b5ca25eb60d36808924ed4'
```

**Comment by JTarasovic** [comment]
But there's definitely something going on.

**Comment by elliottneilclark** [comment]
I think it's space related if the git is a complete red herring.

**Pull request merged**
