### PR TITLE
chore(bi): upgrade to k8s 1.31

### PR DESCRIPTION
**Pull request by JTarasovic**
Test plan:
- [x] Verify cluster is created and bootstraps successfully

### CODE REVIEW

**Review by elliottneilclark — APPROVED** [review]
I assume there are no images that also need to move.

**Comment by JTarasovic** [comment]
Good call. I'll try to spin up everything else to make sure but the install came up perfect so at least a good chunk are good.

**Review by elliottneilclark — CHANGES_REQUESTED** [review]
Sorry for the whiplash. Please also update `pkg/cluster/kind/kind.go` to use the corresponding kind version for kubernetes and make sure that all comes up ok.

**Comment by JTarasovic** [comment]
Lol. Already done. Pushing shortly.

**Review by elliottneilclark — APPROVED** [review]

**Pull request merged**
