### PR TITLE
feat(traditional): add ability to add additional hosts

### PR DESCRIPTION
**Pull request by JTarasovic**

### CODE REVIEW

**Comment by JTarasovic** [comment]
image

```
 k get gateways.networking.istio.io -o yaml -n battery-istio ingressgateway
apiVersion: networking.istio.io/v1
kind: Gateway
...
spec:
  selector:
    istio: ingressgateway
  servers:
 ...
  - hosts:
    - logic-guide-freddie.battery-traditional.webapp.3-12-116-86.batrsinc.co
    - logic-guide-freddie.battery-traditional.webapp.3-16-39-27.batrsinc.co
    - logic-guide-freddie.battery-traditional.webapp.3-20-244-50.batrsinc.co
    - echo.batteriesincl.com
 ```

```
 k get vs -n battery-traditional logic-guide-freddie -o yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
...
spec:
  exportTo: []
  gateways:
  - battery-istio/ingressgateway
  hosts:
  - logic-guide-freddie.battery-traditional.webapp.3-12-116-86.batrsinc.co
  - logic-guide-freddie.battery-traditional.webapp.3-16-39-27.batrsinc.co
  - logic-guide-freddie.battery-traditional.webapp.3-20-244-50.batrsinc.co
  - echo.batteriesincl.com
  http:
  - match: []
    name: fallback
    route:
    - destination:
        host: logic-guide-freddie
        port:
          number: 80
```

```
k get cert -n battery-istio traditional-services-ingress-cert -o yaml
apiVersion: cert-manager.io/v1
kind: Certificate
...
spec:
  dnsNames:
  - logic-guide-freddie.battery-traditional.webapp.3-12-116-86.batrsinc.co
  - logic-guide-freddie.battery-traditional.webapp.3-16-39-27.batrsinc.co
  - logic-guide-freddie.battery-traditional.webapp.3-20-244-50.batrsinc.co
  - echo.batteriesincl.com
```

**Comment by elliottneilclark** [comment]
This will be awesome!

**Comment by JTarasovic** [comment]
```
curl -s https://echo.testing.batteriesincl.com/ | jq '.'
{
  "host": {
    "hostname": "echo.testing.batteriesincl.com",
    "ip": "::ffff:127.0.0.6",
    "ips": []
  },
  "http": {
    "method": "GET",
    "baseUrl": "",
    "originalUrl": "/",
    "protocol": "http"
  },
  "request": {
    "params": {
      "0": "/"
    },
    "query": {},
    "cookies": {},
    "body": {},
    "headers": {
      "host": "echo.testing.batteriesincl.com",
      "user-agent": "curl/8.10.1",
      "accept": "*/*",
      "x-forwarded-for": "100.64.3.162",
      "x-forwarded-proto": "https",
      "x-envoy-external-address": "100.64.3.162",
      "x-request-id": "1cade94f-416c-4188-bfff-e840c8906fdc",
      "x-envoy-attempt-count": "1",
      "x-forwarded-client-cert": "By=spiffe://cluster.local/ns/battery-traditional/sa/brother-secure-doctor-service-account;Hash=076ad40b6c66adc925848aea0fb841d238d390f212d9a540eb7cd40e95598ac5;Subject=\"\";URI=spiffe://cluster.local/ns/battery-istio/sa/istio-ingressgateway-service-account",
      "x-b3-traceid": "a84fbd18c0208abc719252f373369845",
      "x-b3-spanid": "719252f373369845",
      "x-b3-sampled": "0"
    }
  },
  "environment": {
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "HOSTNAME": "brother-secure-doctor-96644c6dd-xnjxr",
    "NODE_VERSION": "20.11.0",
    "YARN_VERSION": "1.22.19",
    "KUBERNETES_SERVICE_HOST": "10.100.0.1",
    "KUBERNETES_SERVICE_PORT_HTTPS": "443",
    "KUBERNETES_PORT": "tcp://10.100.0.1:443",
    "KUBERNETES_PORT_443_TCP_PROTO": "tcp",
    "KUBERNETES_PORT_443_TCP_PORT": "443",
    "BROTHER_SECURE_DOCTOR_SERVICE_PORT_HTTP": "80",
    "BROTHER_SECURE_DOCTOR_PORT_80_TCP_PORT": "80",
    "BROTHER_SECURE_DOCTOR_SERVICE_HOST": "10.100.168.0",
    "BROTHER_SECURE_DOCTOR_SERVICE_PORT": "80",
    "BROTHER_SECURE_DOCTOR_PORT": "tcp://10.100.168.0:80",
    "BROTHER_SECURE_DOCTOR_PORT_80_TCP": "tcp://10.100.168.0:80",
    "BROTHER_SECURE_DOCTOR_PORT_80_TCP_PROTO": "tcp",
    "BROTHER_SECURE_DOCTOR_PORT_80_TCP_ADDR": "10.100.168.0",
    "KUBERNETES_SERVICE_PORT": "443",
    "KUBERNETES_PORT_443_TCP": "tcp://10.100.0.1:443",
    "KUBERNETES_PORT_443_TCP_ADDR": "10.100.0.1",
    "HOME": "/root"
  }
}
```

**Comment by JTarasovic** [comment]
and the original hostname also still works

```
curl -s https://brother-secure-doctor.battery-traditional.webapp.18-190-118-4.batrsinc.co/ | jq '.'
{
  "host": {
    "hostname": "brother-secure-doctor.battery-traditional.webapp.18-190-118-4.batrsinc.co",
    "ip": "::ffff:127.0.0.6",
    "ips": []
  },
  "http": {
    "method": "GET",
    "baseUrl": "",
    "originalUrl": "/",
    "protocol": "http"
  },
  "request": {
    "params": {
      "0": "/"
    },
    "query": {},
    "cookies": {},
    "body": {},
    "headers": {
      "host": "brother-secure-doctor.battery-traditional.webapp.18-190-118-4.batrsinc.co",
      "user-agent": "curl/8.10.1",
      "accept": "*/*",
      "x-forwarded-for": "100.64.3.162",
      "x-forwarded-proto": "https",
      "x-envoy-external-address": "100.64.3.162",
      "x-request-id": "1a670d01-999b-41ce-ab68-c6453b0186c1",
      "x-envoy-attempt-count": "1",
      "x-forwarded-client-cert": "By=spiffe://cluster.local/ns/battery-traditional/sa/brother-secure-doctor-service-account;Hash=076ad40b6c66adc925848aea0fb841d238d390f212d9a540eb7cd40e95598ac5;Subject=\"\";URI=spiffe://cluster.local/ns/battery-istio/sa/istio-ingressgateway-service-account",
      "x-b3-traceid": "db9a24c621659d247c90a09971749288",
      "x-b3-spanid": "7c90a09971749288",
      "x-b3-sampled": "0"
    }
  },
  "environment": {
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "HOSTNAME": "brother-secure-doctor-96644c6dd-xnjxr",
    "NODE_VERSION": "20.11.0",
    "YARN_VERSION": "1.22.19",
    "KUBERNETES_SERVICE_HOST": "10.100.0.1",
    "KUBERNETES_SERVICE_PORT_HTTPS": "443",
    "KUBERNETES_PORT": "tcp://10.100.0.1:443",
    "KUBERNETES_PORT_443_TCP_PROTO": "tcp",
    "KUBERNETES_PORT_443_TCP_PORT": "443",
    "BROTHER_SECURE_DOCTOR_SERVICE_PORT_HTTP": "80",
    "BROTHER_SECURE_DOCTOR_PORT_80_TCP_PORT": "80",
    "BROTHER_SECURE_DOCTOR_SERVICE_HOST": "10.100.168.0",
    "BROTHER_SECURE_DOCTOR_SERVICE_PORT": "80",
    "BROTHER_SECURE_DOCTOR_PORT": "tcp://10.100.168.0:80",
    "BROTHER_SECURE_DOCTOR_PORT_80_TCP": "tcp://10.100.168.0:80",
    "BROTHER_SECURE_DOCTOR_PORT_80_TCP_PROTO": "tcp",
    "BROTHER_SECURE_DOCTOR_PORT_80_TCP_ADDR": "10.100.168.0",
    "KUBERNETES_SERVICE_PORT": "443",
    "KUBERNETES_PORT_443_TCP": "tcp://10.100.0.1:443",
    "KUBERNETES_PORT_443_TCP_ADDR": "10.100.0.1",
    "HOME": "/root"
  }
}
```

**Pull request merged**
